#!/bin/bash

set -e

ELLIPTICS_VERSION=2.25.5.1

cat > /etc/apt/sources.list.d/reverbrain.list <<EOF
deb http://repo.reverbrain.com/trusty/ current/amd64/
deb http://repo.reverbrain.com/trusty/ current/all/
EOF

wget -qO- http://repo.reverbrain.com/REVERBRAIN.GPG | apt-key add -

apt-get -y update
apt-get install -y elliptics="${ELLIPTICS_VERSION}" \
  elliptics-client="${ELLIPTICS_VERSION}"
