#!/bin/bash
set -e

IP=$(cat /etc/hosts | grep "${HOSTNAME}" | awk '{ print $1 }')

#some directories
echo $IP
mkdir /tmp/history/
mkdir /tmp/root
mkdir -p /opt/elliptics/eblob.2
# touch /opt/elliptics/eblob.2/data
mkdir /opt/elliptics/history.2

sed -i "s,{{IP}},""${IP}"",g" -i /app/setup/ioserv.json

appStart () {

  dnet_ioserv -c /app/setup/ioserv.json

}

appHelp () {
  echo "Available options:"
  echo "  app:start          - Starts the elliptics (default)"
  echo "  app:help           - Displays the help"
  echo "  [command]          - Execute the specified linux command eg. bash"
}

case "$1" in
  app:start)
    appStart
    ;;
  app:help)
    appHelp
    ;;
  *)
    if [ -x $1 ]; then
      $1
    else
      prog=$(which $1)
      if [ -n "${prog}" ] ; then
        shift 1
        $prog $@
      else
        appHelp
      fi
    fi
    ;;
esac

exit 0
